export { default as Header } from './Header.vue'
export { default as Footer } from './Footer.vue'
export { default as Banner } from './Banner.vue'
export { default as SubCategory } from './SubCategory/index.vue'
export { default as SubPost } from './SubPost/index.vue'
export { default as AdminHeader } from './admin/Header.vue'
export { default as AdminSubPost } from './admin/AdminSubPost/index.vue'